2025-04-07 11:46:10,746 - INFO - Logging to file: /home/dogdorgesh/Documents/Github/Tandem-Repeat-Domain-Database/col_data/logs/ensembl_api_20250407_114610.log
2025-04-07 11:46:10,747 - INFO - Found 0 existing cache files
2025-04-07 11:46:10,752 - ERROR - Script failed with error:
Traceback (most recent call last):
  File "/home/dogdorgesh/Documents/Github/Tandem-Repeat-Domain-Database/col_data/scripts/exon_info.py", line 707, in <module>
    process_repeat_data(input_file, output_file, limit=limit)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dogdorgesh/Documents/Github/Tandem-Repeat-Domain-Database/col_data/scripts/exon_info.py", line 464, in process_repeat_data
    with open(repeat_data_file, 'r') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dogdorgesh/Documents/Github/Tandem-Repeat-Domain-Database/col_data/output/1test.json'
