2025-03-11 14:52:31,397 - INFO - Logging to file: c:\Users\ojfab\Documents\GitHub\Tandem-Repeat-Domain-Database\merge_test_small\logs\ensembl_api_20250311_145231.log
2025-03-11 14:52:31,397 - ERROR - Script failed with error:
Traceback (most recent call last):
  File "c:\Users\ojfab\Documents\GitHub\Tandem-Repeat-Domain-Database\merge_test_small\scripts\exon_info.py", line 483, in <module>
    process_repeat_data(input_file, output_file, limit=None)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ojfab\Documents\GitHub\Tandem-Repeat-Domain-Database\merge_test_small\scripts\exon_info.py", line 295, in process_repeat_data
    with open(repeat_data_file, 'r') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\ojfab\\Documents\\GitHub\\Tandem-Repeat-Domain-Database\\merge_test_small\\data\\gname_hg38_repeats_100.json'
